Lenke til utbetalinger
navikt/sykefravaer pull request #378
Opened 2020-09-18 07:53 UTC by golshidb93

2020-09-18 07:57 UTC, heyvard commented on js/enums/dokumentTyper.js
> +export const SYKMELDING = 'Sykmelding';
trengs denne fila?

2020-09-18 08:01 UTC, heyvard requested changes
Slå også gjerne sammen commit historikken

2020-09-18 08:01 UTC, heyvard commented on js/utils/urlUtils.js
> +    return process.env.REACT_APP_SPINNSYN_ROOT;
Dette vil ikke funke i q1 og prod. Adressen til spinnsyn frontend ligger ikke under tjenester.nav.no slik som denne appen gjør

2020-09-18 08:01 UTC, heyvard commented on mock/mockSyforest.js
> +    server.get('/syforest/vedtak', (req, res) => {
Litt rart å putte denne under syforest fordi disse vedtakene hentes ikke fra syforest. Men det er også greit å teste at dette vil funke på opplæringsversjonen

2020-09-18 08:02 UTC, heyvard commented on js/enums/dokumentTyper.js
> +export const SYKMELDING = 'Sykmelding';
Skjønte hvorfor den er her nå

2020-09-18 12:12 UTC, heyvard requested changes

2020-09-18 12:12 UTC, heyvard commented on js/utils/urlUtils.js
> +        return process.env.REACT_APP_SPINNSYN_ROOT;
Kan denne bare hardkodes istedenfor så slipper vi den react app variabelen? Den skal jo aldri endre seg

2020-09-23 10:41 UTC, heyvard approved these changes

2020-09-23 10:47 UTC, golshidb93 commented
Lenker sykefravær til vedtak (sykepengeinnsyn)

2020-09-23 10:49 UTC, merged