Sykmeldinger backend ny url
navikt/sykefravaer pull request #394
Opened 2020-12-04 14:45 UTC by sebdak

Henter sykmeldinger fra sykmeldinger-backend hvis toggle `syfo.syfofront.sykmeldinger.backend` er på.

Må huske å senke toggle-rate ned fra 100% til noe lavere!!

2020-12-07 07:41 UTC, heyvard requested changes

2020-12-07 07:41 UTC, heyvard commented on js/sykmeldinger/data/dine-sykmeldinger/dineSykmeldingerSagas.js
> +        return 'https://sykmeldinger-backend-proxy.dev.nav.no/api/v1/syforest';
dette er ikke prod :)

2020-12-07 07:41 UTC, heyvard commented on js/sykmeldinger/data/dine-sykmeldinger/dineSykmeldingerSagas.js
> +        return 'https://sykmeldinger-backend-proxy.dev.nav.no/api/v1/syforest';
Dere må også sette opp DNS.  https://sykmeldinger-backend-proxy.nav.no/isAlive svarer ikke

Anbefaler også nyere versjon av flex-proxy, varianten dere kjører er litt alpha og slet med connections, satt opp for mange på nytt som var uheldig over lengre avstand, bytta over til en spring variant (som trenger mer minne). Se repoet, skal ish holde å bumpe cpu, minne og FROM i Dockerfile

2020-12-07 07:41 UTC, heyvard commented on js/sykmeldinger/data/dine-sykmeldinger/dineSykmeldingerSagas.js
> +        // return 'http://localhost:6969/syfosmregister/api';
return 'http://localhost:6998/api/v1/syforest'

2020-12-07 07:41 UTC, heyvard commented on js/sykmeldinger/data/dine-sykmeldinger/dineSykmeldingerSagas.js
> +        // return 'http://localhost:6969/syfosmregister/api';
return 'http://localhost:6998/api/v1/syforest'

2020-12-07 07:42 UTC, heyvard commented on js/sykmeldinger/data/dine-sykmeldinger/dineSykmeldingerSagas.js
> +        return 'https://sykmeldinger-backend-proxy.dev.nav.no/api/v1/syforest';
Og endre fra epxress.js til spring syntax i routes.yaml

2020-12-08 06:43 UTC, tiafiring approved these changes

2020-12-09 08:01 UTC, andreasDev approved these changes

2020-12-14 09:20 UTC, johenie approved these changes

2020-12-14 10:09 UTC, merged