Lagt til reisetilskudd i oppgavelisten
navikt/sykefravaer pull request #407
Opened 2021-01-29 12:20 UTC by kjarbr

2021-01-29 13:57 UTC, heyvard requested changes

2021-01-29 13:57 UTC, heyvard commented on js/landingsside/dine-oppgaver/DineOppgaverContainer.js
> +    const tekst = alleSoknader.length === 1
denne vil jo vise for absolutt alle søknader? Jeg ser for meg forskjellig tekst på ÅPEN og SENDBAR, men det bør Bendik men noe om

2021-02-03 12:39 UTC, golshidb93 approved these changes

2021-02-03 12:54 UTC, chinatsu approved these changes

2021-03-16 07:35 UTC, closed without merging